apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
        - name: post-container
          image: abdul303subhan/post:latest
          ports:
            - containerPort: 3000
